### PR TITLE
Update TargetFramework to 2.2

### PR DESCRIPTION
**Pull request by adiaaida**

### CODE REVIEW

**Comment by rynowak** [comment]
```
C:\projects\jitbench\CreateStore.proj : error NU1202: Package Microsoft.NETCore.App 2.2.0-preview1-26611-03 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package Microsoft.NETCore.App 2.2.0-preview1-26611-03 supports: netcoreapp2.2 (.NETCoreApp,Version=v2.2)
C:\projects\jitbench\CreateStore.proj : error NU1202: Package Microsoft.NETCore.App 2.2.0-preview1-26611-03 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1) / win7-x64. Package Microsoft.NETCore.App 2.2.0-preview1-26611-03 supports: netcoreapp2.2 (.NETCoreApp,Version=v2.2)
  Generating MSBuild file C:\projects\jitbench\.temp\Optimize\CreateStore.proj.nuget.g.props.
  Generating MSBuild file C:\projects\jitbench\.temp\Optimize\CreateStore.proj.nuget.g.targets.
  Restore failed in 2.68 sec for C:\projects\jitbench\CreateStore.proj.
dotnet store failed.
```

Is there another hardcoded `netcoreapp2.1` somewhere?

**Comment by adiaaida** [comment]
@rynowak Yeah, I missed the hard-coded bits in AspNet-GenerateStore. Locally, I was specifying netcoreapp2.2 with -Framework.

**Comment by adiaaida** [comment]
@rynowak I've updated the ci scripts, so this change is good to go now.

**Comment by rynowak** [comment]
Cool 👍

**Pull request merged**
