### PR TITLE
Update install scripts

### PR DESCRIPTION
**Pull request by rynowak**

### CODE REVIEW

**Comment by JosephTremoulet** [comment]
Would it be better for this repo to have a wrapper/bootstrapper script that just uses `Invoke-WebRequest -Uri https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.ps1` to always get the latest install script?

**Comment by rynowak** [comment]
We could do something like that.... I don't want to deviate too far from the set of steps and tools that are already publicly documented. 

https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-install-script.md

We recently had the same discussion on for the ASP.NET build system and ultimately decided that the scripts are updated infrequently enough we didn't need/want to automate it.

**Comment by JosephTremoulet** [comment]
> We recently had the same discussion on for the ASP.NET build system and ultimately decided that the scripts are updated infrequently enough we didn't need/want to automate it

Ah.  In that case, yeah, following suit here makes sense, no need to rehash the issue.  Thanks.

**Comment by rynowak** [comment]
> Ah. In that case, yeah, following suit here makes sense, no need to rehash the issue. Thanks.

Long term I think the goal is for the acquisition to be rolled into `dotnet` itself, which is the shining future that we're all waiting for 👍

**Comment by rynowak** [comment]
Waiting for the build to be green here, apparently it's not clear yet whether these are fully working or not. /cc @kichalla

**Comment by kichalla** [comment]
@rynowak an update was made to the CLI scripts few minutes back. That fixed the issue I was talking about earlier.

**Comment by rynowak** [comment]
Thanks, I'll update again and try it.

**Pull request merged**
