### PR TITLE
Fix MusicStore build using latest cli, and enable build on linux

### PR DESCRIPTION
**Pull request by sbomer**
The in-memory database change is taken from https://github.com/aspnet/MusicStore/commit/9c676187f6698c781693723fcf2c7b138151e0f3.
Without this, I can't build using the latest cli:

```
Microsoft (R) Build Engine version 15.2.2.21747
Copyright (C) Microsoft Corporation. All rights reserved.

/home/sven/bin/sdk/2.0.0-alpha-005156/Microsoft.Common.CurrentVersion.targets(1951,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [/home/sven/src/dotnet/linker/musicstore/JitBench/src/MusicStore/MusicStore.csproj]
StartupOpenIdConnect.cs(60,37): error CS1501: No overload for method 'UseInMemoryDatabase' takes 0 arguments [/home/sven/src/dotnet/linker/musicstore/JitBench/src/MusicStore/MusicStore.csproj]
Startup.cs(43,29): error CS1501: No overload for method 'UseInMemoryDatabase' takes 0 arguments [/home/sven/src/dotnet/linker/musicstore/JitBench/src/MusicStore/MusicStore.csproj]

```

Also avoid running the crossgen powershell script so that we can build on linux.

@russellhadley ,@erozenfeld,@swaroop-sridhar,@rynowak

### CODE REVIEW

**Comment by erozenfeld** [comment]
LGTM

**Comment by JosephTremoulet** [comment]
LGTM too

**Comment by sbomer** [comment]
Could someone merge this, maybe @rynowak? I don't have access.

**Comment by erozenfeld** [comment]
I believe @JosephTremoulet has write access.

**Comment by JosephTremoulet** [comment]
I do not. @rynowak has merged all the changes I authored.

**Comment by rynowak** [comment]
:shipit:  thanks!

**Pull request merged**
